FROM ubuntu:16.04

RUN apt-get update -qq && \
    apt-get install -y apache2 libapache2-mod-php7.0 php7.0-cli php7.0-mbstring php7.0-sqlite3 \
    php7.0-opcache php7.0-json php7.0-mysql php7.0-pgsql php7.0-ldap php7.0-gd php7.0-iconv curl unzip && \
    apt-get clean && \
    echo "ServerName localhost" >> /etc/apache2/apache2.conf && \
    sed -ri 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf && \
    a2enmod rewrite && \
    curl -sS https://getcomposer.org/installer | php -- --filename=/usr/local/bin/composer

RUN cd /var/www \
    && rm -rf /var/www/html \
    && curl -sLO https://github.com/kanboard/kanboard/archive/master.zip \
    && unzip -qq master.zip \
    && rm -f *.zip \
    && mv kanboard-master html \
    && cd /var/www/html && composer --prefer-dist --no-dev --optimize-autoloader --quiet install \
    && chown -R www-data:www-data /var/www/html/data

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

EXPOSE 80

VOLUME /var/www/html/data
VOLUME /var/www/html/plugins

CMD /usr/sbin/apache2ctl -D FOREGROUND
