FROM fguillot/alpine-nginx-php7

ENV KANBOARD_VERSION 1.0.46
ENV KANBOARD_TARBALL https://github.com/kanboard/kanboard/archive/v${KANBOARD_VERSION}.tar.gz

RUN mkdir -p /var/www/app \
  && curl -sLo - \
  ${KANBOARD_TARBALL} | tar -xzf - --strip 1 -C /var/www/app

WORKDIR /var/www/app
RUN composer --prefer-dist --no-dev --optimize-autoloader install && \
    chown -R nginx:nginx /var/www/app && \
    ./cli plugin:install https://github.com/kanboard/plugin-beanstalk/releases/download/v1.0.0/Beanstalk-1.0.0.zip

COPY files/kanboard/postgres_beanstalk.php /var/www/app/config.php
COPY files/crontab/cronjob.alpine /var/spool/cron/crontabs/nginx
COPY files/services.d/cron /etc/services.d/cron
COPY files/services.d/worker /etc/services.d/worker

VOLUME /var/www/app/data
VOLUME /var/www/app/plugins
