FROM alpine:3.4

RUN apk update && \
    apk add nginx bash ca-certificates s6 curl \
    php5-fpm php5-json php5-zlib php5-xml php5-dom php5-ctype php5-opcache php5-zip \
    php5-pdo php5-pdo_mysql php5-pdo_sqlite php5-pdo_pgsql php5-ldap \
    php5-gd php5-mcrypt php5-openssl php5-phar && \
    rm -rf /var/cache/apk/*

RUN cd /var/www \
    && curl -sLO https://kanboard.net/kanboard-latest.zip \
    && unzip -qq kanboard-latest.zip \
    && rm -f *.zip \
    && chown -R nginx:nginx /var/www/kanboard \
    && chown -R nginx:nginx /var/lib/nginx

COPY files/services.d /etc/services.d
COPY files/php/conf.d/local.ini /etc/php5/conf.d/
COPY files/php/php-fpm.conf /etc/php5/
COPY files/nginx/nginx.conf /etc/nginx/
COPY files/kanboard/config.php /var/www/kanboard/
COPY files/kanboard/config.php /var/www/kanboard/
COPY files/crontab/kanboard /var/spool/cron/crontabs/nginx

EXPOSE 80

VOLUME /var/www/kanboard/data
VOLUME /var/www/kanboard/plugins

ENTRYPOINT ["/bin/s6-svscan", "/etc/services.d"]
CMD []
